// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_messagecontent_allowhtml : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_messagecontent_allowhtml));
        
        string IMigrationMetadata.Id
        {
            get { return "202408130959212_mig_messagecontent_allowhtml"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
